
services:
  
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/etc/traefik:ro
      - ./certs:/etc/letsencrypt
    restart: unless-stopped
  
  db:
    container_name: "db"
    image: "postgres:17"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      #Здесь возможно будет лучше поменять на "5433:${DB_PORT}", так как на сервере может быть 5432 уже быть занят другой POSTGRES
      - "${DB_PORT}:${DB_PORT}" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_project:/var/lib/postgresql/data
  
  adminservice:
    build:
      context: ./backend/adminService
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - 8001
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminservice.entrypoints=websecure"
      - "traefik.http.routers.adminservice.rule=Host(`${HOST}`) && PathPrefix(`/admin`)"
      - "traefik.http.services.adminservice.loadbalancer.server.port=8001"
      - "traefik.http.routers.adminservice.tls=true"
      - "traefik.http.routers.adminservice.tls.certresolver=le"
    volumes:
      - static_volume:/admin_service/staticfiles
      - media_volume:/admin_service/mediafiles

  nginx:
      build: ./config/nginx
      restart: unless-stopped
      volumes:
        - static_volume:/admin_service/staticfiles
        - media_volume:/admin_service/mediafiles
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.rule=Host(`${HOST}`) && PathPrefix(`/staticfiles`) || PathPrefix(`/media`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=1337"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.tls.certresolver=le"
      depends_on:
        - adminservice

  backend:
    container_name: "backend"
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.rule=Host(`${HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
    
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`${HOST}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"

volumes:
  pg_project:
  static_volume:
  media_volume: